create table public.meteo_telegram
(
    id_telegram integer,
    station_id integer,
    dt date,
    year integer,
    month integer,
    day integer,
    hour integer,
    telegram varchar(255),
    date_telegram jsonb,
    temperature float,
    dew_point_temperature float,
    relative_humidity float,
    wind_dir float,
    wind_speed float,
    pressure float,
    sea_level_pressure float,
    maximum_temperature float,
    minimum_temperature float,
    precipitation_s1 jsonb,
    precipitation_s3 jsonb,
    pressure_tendency jsonb,
    present_weather float,
    past_weather_1 float,
    past_weather_2 float,
    sunshine float,
    ground_state_snow jsonb,
    ground_state jsonb
);